# Generated by Django 3.1.1 on 2020-09-17 20:53

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='Product_image/')),
                ('price', models.DecimalField(decimal_places=1, max_digits=5)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
